name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: SetupNode
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: SetupPHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2
    - name: Deps
      run: npm ci
    - name: Build
      run: npm run build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run release